name: Microservice Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  update_microservice:
    runs-on: ubuntu-latest
    env:
      LEANIX_API_TOKEN: ${{ secrets.LEANIX_API_TOKEN }}
      LEANIX_SUBDOMAIN: ${{ vars.LEANIX_SUBDOMAIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      - name: Run script
        run: python leanix_assistant.py
